stages:
  - build
  - deploy

build_app:
  stage: build
  tags:
    - hello
  script:
    - echo "build docker image"
    - docker build -t app:latest .
  only:
    - main
deploy_app:
  stage: deploy
  tags:
    - hello
  script:
    - echo "==========deploy app to server================"
    - sudo rm -rf /var/www/html/*
    - sudo mkdir -p var/www/html
    - sudo cp -r static/* var/www/html
    - sudo cp templates/* var/www/html
    - systemctl reload nginx


    - echo "==========deploy app to server successfully================"

    - echo "==========deploy app ================"


    - docker run -d -p 3000:3000 --name app app:latest


    - echo "==========deploy app successfully==============="

    
  only:
    - main

